// <auto-generated />
using System;
using ColaPodNaem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ColaPodNaem.Migrations
{
    [DbContext(typeof(avtoparkColiClientyDbContext))]
    [Migration("20200308082850_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ColaPodNaem.Model.Car", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<decimal>("PriceNaem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("YearMaking")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ColaPodNaem.Model.Client", b =>
                {
                    b.Property<string>("Kola")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CreditCard")
                        .IsRequired()
                        .HasColumnName("CreditCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Karta")
                        .HasColumnName("LichnaKarta")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("VzetaData")
                        .HasColumnName("Data")
                        .HasColumnType("datetime2");

                    b.HasKey("Kola");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ColaPodNaem.Model.Client", b =>
                {
                    b.HasOne("ColaPodNaem.Model.Car", "Car")
                        .WithOne("Client")
                        .HasForeignKey("ColaPodNaem.Model.Client", "Kola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
